name: Deploy
on:
  push:
    branches:
      - main # main ブランチにpushされたらデプロイを実行

jobs:
  deploy:
    name: Deploy to server

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }} # FTPアカウントのホスト名
          username: ${{ secrets.FTP_USERNAME }} # FTPアカウント名
          password: ${{ secrets.FTP_PASSWORD }} # FTPアカウントのパスワード
          local-dir: ./public/
          server-dir: /yukike.com/
          # exclude: "[**/.**/**, .gitignore,  **/.git/**, **/node_modules/**, **/vendor/**, .editorconfig, README.md, .phpcs.xml.dist, **.json, **.lock, postcss.config.js, **/src/**]"

      - name: whoami
        run: whoami

      - name: ls lha
        run: ls -lha /